#!/system/bin/sh
# AIK-mobile/unpackimg: split image and unpack ramdisk
# osm0sis @ xda-developers

menu() {

e="\x1b[";c=$e"39;49;00m";y=$e"93;01m";cy=$e"96;01m";r=$e"1;91m";g=$e"92;01m";

aik=/data/local/AIK-mobile;

mount -o remount,rw /system;


    # go local and request root
    echo ""
    echo $cy"                 ******************              "
    echo $r"                 === AIK-mobile ===              "
    echo $g"==================================================="
    echo "= USAGE :                                         ="
    echo "= BACKUP => backup <enter>                        ="
    echo "= UNPACK => unpack <file.img> <enter>             ="
    echo "= REPACK => repack <enter>                        ="
    echo "= ++++/+++++/++++++/+++++/+++++++/++++++/+++++/++ ="
    echo "= +YOUR WORK FOLDER IN /data/local/AIK-mobile/+++ ="
    echo "=                                                 ="
    echo "============== modified by Rivv ==================="
    echo ""
    echo ""
    #cd $aik;
    echo $y" >> List available image << "
    echo $g""
    ls $aik | grep img
    echo $y""
    #PATH="$PATH:$aik" su;
}

echo ""
echo "====== UNPACK IMAGE ======="
echo " Buat Folder (ketik nama folder)..."
read a
if [ -d $a ]; then
  rm -r $a
  mkdir $a
else
  mkdir $a
fi;

case $0 in
  *.sh) aik="$0";;
     *) aik="$(lsof -p $$ 2>/dev/null | grep -o '/.*unpack$')";;
esac;
aik="$(dirname "$(readlink -f "$aik")")";

cleanup() { rm -rf ramdisk split_img *new.*; }
abort() { cd "$aik"; echo "Error!"; }

cd "$aik";
bb=bin/busybox;
chmod -R 755 bin *.sh;
chmod 644 bin/magic;

if [ ! -f $bb ]; then
  bb=busybox;
else
  rel="$aik/";
fi;

img="$1";
if [ ! "$img" ]; then
  for i in *.img; do
    test "$i" == "image-new.img" && continue;
    img="$i"; break;
  done;
fi;
if [ ! -f "$img" ]; then
  echo "No image file supplied.";
  abort;
  return 1;
fi;

case $0 in *) clear;; esac;
echo "\nAndroid Image Kitchen - UnpackImg Script";
echo "by osm0sis @ xda-developers\n";

file=$($bb basename "$img");
echo "Supplied image: $file\n";

if [ -d split_img -o -d ramdisk ]; then
  echo "Removing old work folders and files...\n";
  cleanup;
fi;

echo "Setting up work folders...\n";
mkdir $a/split_img $a/ramdisk;

echo "Splitting image to \"$a/split_img\"...\n";
bin/unpackbootimg -i "$img" -o $a/split_img;
if [ $? != "0" ]; then
  cleanup;
  abort;
  return 1;
fi;

cd $a/split_img;
$aik/bin/file -m $aik/bin/magic *-ramdisk.gz | $rel$bb cut -d: -f2 | $rel$bb awk '{ print $1 }' > "$file-ramdiskcomp";
ramdiskcomp=`cat *-ramdiskcomp`;
unpackcmd="$rel$bb $ramdiskcomp -dc";
compext=$ramdiskcomp;
case $ramdiskcomp in
  gzip) compext=gz;;
  lzop) compext=lzo;;
  xz) ;;
  lzma) ;;
  bzip2) compext=bz2;;
  lz4) unpackcmd="$aik/bin/lz4 -dq"; extra="stdout";;
  *) compext="";;
esac;
if [ "$compext" ]; then
  compext=.$compext;
fi;
mv "$file-ramdisk.gz" "$file-ramdisk.cpio$compext";
cd $aik;

echo "\nUnpacking ramdisk to \"$a/ramdisk\"...\n";
cd $a/ramdisk;
echo "Compression used: $ramdiskcomp";
if [ ! "$compext" ]; then
  abort;
  return 1;
fi;
$unpackcmd "$aik/$a/split_img/$file-ramdisk.cpio$compext" $extra | $rel$bb cpio -i 2>&1;
if [ $? != "0" ]; then
  abort;
  return 1;
fi;
cd $aik;

echo "\nDone!";
menu
return 0;
